version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3001"
    environment:
      CONFIG_DIR: /app/src/config/
    # network_mode: "host"
    volumes:
      - ./backend/ppserver/src:/app/ppserver/src
      - ./backend/ppserver/.env:/app/ppserver/.env
    # command: npm run dev
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     # Just the folders that you don't edit inside the container
  #     - ./frontend/ppfront/src:/app/ppfront/src:rw
  #     - ./frontend/ppfront/public:/app/ppfront/public:rw
  #   command: npm run dev