version: '3'

services:
  backend:
    build: ./backend
    # ports:
    #   - "5001:3001"
    environment:
      CONFIG_DIR: /app/src/config/
    # network_mode: "host"  # Uncomment this line if needed
    networks:
      - mynetwork
    volumes:
      - ./backend/ppserver/src:/app/ppserver/src
      - ./backend/ppserver/.env:/app/ppserver/.env

  frontend:
    build: ./frontend
    # ports:
    #   - "5000:3000"
    networks:
      - mynetwork
    volumes:
      - ./frontend/ppfront/src:/app/ppfront/src:rw
      - ./frontend/ppfront/public:/app/ppfront/public:rw
  
  mongodb:
    image: mongo
    ports:
      - "27016:27016"
    environment:
    MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - ./mongo_creds.env
    networks:
      - mynetwork
    volumes:
      - ./mongodb:/data/db

  reverse-proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend

networks:
  mynetwork:
    driver: bridge

